In [22]:
import numpy as np

v1 = np.array([0, 0, 2])
v2 = np.array([0, 1, 1])

In [8]:
from numpy import dot
from numpy.linalg import norm

# 실제 사용 시 def get_cosine_similarity(features):
def get_cosine_similarity(A, B):
    return dot(A, B) / (norm(A) * norm(B))

In [23]:
get_cosine_similarity(v1, v2)

0.7071067811865475

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

v1 = np.array([[0, 0, 2]])
v2 = np.array([[0, 1, 1]])
cosine_similarity(v1, v2)

array([[0.70710678]])

In [26]:
import numpy as np 
import pandas as pd

# 텍스트 분석이기 때문에 텍스트와 관련된 컬럼은 있어야 함
m_df = pd.read_csv('./datasets/movie_dataset.csv')
m_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [27]:
m_df.overview

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...                        
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: object

In [29]:
m_df.isna().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [31]:
# genres, keywords, overview, tagline, cast, director

columns = ['genres', 'keywords', 'overview', 'tagline', 'cast', 'director']

pre_m_df =m_df[columns].fillna('')
pre_m_df.isna().sum()

genres      0
keywords    0
overview    0
tagline     0
cast        0
director    0
dtype: int64

In [34]:
columns = ['genres', 'keywords', 'overview', 'tagline', 'cast', 'director']
features = pre_m_df.loc[:, columns]

def concatenate(features):
    return features.genres + ' ' + features.keywords + ' ' + \
    features.overview + ' ' + features.tagline + ' ' + \
    features.cast + features.director

concatenate(features)

result_df = concatenate(features)

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_v = CountVectorizer()
count_metrix = count_v.fit_transform(result_df)
print(count_metrix)

c_s = cosine_similarity(count_metrix)
print(c_s)
c_s.shape

  (0, 569)	1
  (0, 719)	1
  (0, 10758)	1
  (0, 26821)	1
  (0, 11063)	1
  (0, 7309)	1
  (0, 5852)	1
  (0, 11924)	1
  (0, 28402)	2
  (0, 32785)	1
  (0, 6198)	1
  (0, 28213)	1
  (0, 15084)	1
  (0, 30242)	3
  (0, 239)	1
  (0, 5280)	1
  (0, 22547)	1
  (0, 19116)	1
  (0, 15642)	1
  (0, 8653)	1
  (0, 30558)	1
  (0, 20520)	1
  (0, 22473)	2
  (0, 21951)	1
  (0, 31856)	1
  :	:
  (4802, 10575)	1
  (4802, 23989)	1
  (4802, 10130)	1
  (4802, 26968)	1
  (4802, 6784)	1
  (4802, 15994)	1
  (4802, 4231)	1
  (4802, 9121)	3
  (4802, 2679)	3
  (4802, 25798)	1
  (4802, 11136)	1
  (4802, 11859)	1
  (4802, 12968)	1
  (4802, 1929)	1
  (4802, 7830)	1
  (4802, 26617)	1
  (4802, 1914)	1
  (4802, 8793)	1
  (4802, 250)	1
  (4802, 7240)	2
  (4802, 10934)	1
  (4802, 12768)	1
  (4802, 4728)	1
  (4802, 14044)	4
  (4802, 9294)	1
[[1.         0.3633256  0.23428783 ... 0.29563906 0.21788191 0.12302219]
 [0.3633256  1.         0.33596842 ... 0.39413729 0.29508445 0.17039954]
 [0.23428783 0.33596842 1.         ... 0.245918

(4803, 4803)

In [49]:
def get_index_from_title(title):
    return m_df[m_df.title == title].index[0]


def get_title_from_index(index):
    return m_df[m_df.index == index]['title'].values[0]


movie_title = "Men in Black"
movie_index = get_index_from_title(movie_title)
recommended_movie = sorted(list(enumerate(c_s[movie_index])),key = lambda x: x[1], reverse=True)
recommended_movie

for movie in recommended_movie[1:6]:
    print(get_title_from_index(movie[0]))

# get_index_from_title("Pirates of the Caribbean: At World's End")

Men in Black II
Space Battleship Yamato
The Hobbit: The Battle of the Five Armies
The Work and the Glory II: American Zion
The Andromeda Strain
